# -*- coding: utf-8 -*-
"""N-gram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15r57eQ55dAblOMN-GwficSJYaGTxmXTV
"""

import pandas as pd
from collections import Counter
from itertools import islice

# 1. 데이터 불러오기
# =========================================================

file_path = "/content/alt_preprocessing.csv"

df = pd.read_csv(file_path, encoding="cp949")

print("데이터 크기:", df.shape)
print("\n컬럼 목록:")
print(df.columns.tolist())

# 카테고리별 사용할 모델과 전처리 컬럼
model_config = {
    "bakery": {
        "qwen3": "qwen_3_deepl_KOR_processed_tokens"
    },

    "fruits_nuts_rice": {
        "qwen3": "qwen_3_deepl_KOR_processed_tokens",
        "hyperclovax": "HyperCLOVAX_KOR_processed_tokens"
    },

    "convenience_meals": {
        "hyperclovax": "HyperCLOVAX_KOR_processed_tokens"
    },

    "vegetables": {
        "hyperclovax": "HyperCLOVAX_KOR_processed_tokens"
    }
}

import ast
import re

def convert_to_tokens(value):

    if pd.isna(value):
        return []

    value = str(value).strip()

    if value == "":
        return []

    # 문자열로 저장된 리스트를 실제 리스트로 변환
    if value.startswith("[") and value.endswith("]"):
        try:
            tokens = ast.literal_eval(value)

            if isinstance(tokens, list):
                cleaned_tokens = []

                for token in tokens:
                    token = str(token).strip()

                    # 토큰 양쪽의 불필요한 기호 제거
                    token = token.strip("[]'\" ,")

                    if token:
                        cleaned_tokens.append(token)

                return cleaned_tokens

        except (ValueError, SyntaxError):
            pass

    # 리스트 형태가 아닌 경우
    tokens = value.split()

    cleaned_tokens = []

    for token in tokens:
        token = token.strip("[]'\" ,")

        if token:
            cleaned_tokens.append(token)

    return cleaned_tokens

# 4.N-gram 생성
def make_ngrams(tokens, n):

    if len(tokens) < n:
        return []

    return [
        " ".join(tokens[i:i+n])
        for i in range(len(tokens) - n + 1)
    ]

# =========================================================
# 5. 카테고리별 N-gram 생성
# =========================================================

def generate_ngram(df, model_config, n):

    results = []

    for category, models in model_config.items():

        category_df = df[
            df["category"] == category
        ].copy()

        print(f"\n[{category}]")
        print(f"데이터 수: {len(category_df)}")

        for model_name, text_column in models.items():

            print(f"  모델: {model_name}")
            print(f"  사용 컬럼: {text_column}")

            if text_column not in df.columns:
                print(f"  ⚠️ 컬럼이 존재하지 않습니다: {text_column}")
                continue

            for _, row in category_df.iterrows():

                # 전처리된 토큰 가져오기
                tokens = convert_to_tokens(
                    row[text_column]
                )

                # N-gram 생성
                ngrams = make_ngrams(
                    tokens,
                    n
                )

                # 동일 N-gram의 등장 횟수 계산
                ngram_counts = Counter(ngrams)

                # 결과 저장
                for keyword, count in ngram_counts.items():

                    results.append({
                        "category": row["category"],
                        "model": model_name,
                        "product_id": row["product_id"],
                        "image_order": row["image_order"],
                        "n_gram_keyword": keyword,
                        "ngram_count": count
                    })

    return pd.DataFrame(results)

# 1-gram
ngram_1 = generate_ngram(
    df,
    model_config,
    n=1
)

# 2-gram
ngram_2 = generate_ngram(
    df,
    model_config,
    n=2
)

# 3-gram
ngram_3 = generate_ngram(
    df,
    model_config,
    n=3
)

ngram_1.to_csv(
    "/content/ngram_1.csv",
    index=False,
    encoding="utf-8-sig"
)

ngram_2.to_csv(
    "/content/ngram_2.csv",
    index=False,
    encoding="utf-8-sig"
)

ngram_3.to_csv(
    "/content/ngram_3.csv",
    index=False,
    encoding="utf-8-sig"
)

print("N-gram CSV 저장 완료")

print("1-gram:", ngram_1.shape)
print("2-gram:", ngram_2.shape)
print("3-gram:", ngram_3.shape)

# 특정 제품의 2-gram 확인
ngram_2[
    ngram_2["product_id"] == ngram_2["product_id"].iloc[0]
].sort_values(
    "ngram_count",
    ascending=False
)

