# -*- coding: utf-8 -*-
"""TF-IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZuKHSmq9KxLpc0JuflMMXbtpinMZV9_
"""

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfTransformer

from pathlib import Path

ngram_1 = pd.read_csv(
    "/content/ngram_1.csv",
    encoding="utf-8-sig"
)

ngram_2 = pd.read_csv(
    "/content/ngram_2.csv",
    encoding="utf-8-sig"
)

ngram_3 = pd.read_csv(
    "/content/ngram_3.csv",
    encoding="utf-8-sig"
)

display(ngram_1.head())
display(ngram_2.head())
display(ngram_3.head())

def calculate_tfidf(ngram_df):

    all_results = []

    # category + model별로 TF-IDF 계산
    for (category, model), group_df in ngram_df.groupby(
        ["category", "model"]
    ):

        print(f"\n현재 그룹: {category} + {model}")
        print(f"데이터 수: {len(group_df)}")

        group_df = group_df.copy()

        # 이미지 하나를 하나의 문서로 구분
        group_df["image_id"] = (
            group_df["product_id"].astype(str)
            + "_"
            + group_df["image_order"].astype(str)
        )

        # 이미지 × N-gram count matrix 생성
        count_matrix = group_df.pivot_table(
            index="image_id",
            columns="n_gram_keyword",
            values="ngram_count",
            aggfunc="sum",
            fill_value=0
        )

        # TF-IDF 계산
        transformer = TfidfTransformer()

        tfidf_matrix = transformer.fit_transform(
            count_matrix
        )

        # DataFrame으로 변환
        tfidf_df = pd.DataFrame(
            tfidf_matrix.toarray(),
            index=count_matrix.index,
            columns=count_matrix.columns
        )

        # Wide → Long 형태
        tfidf_long = tfidf_df.reset_index().melt(
            id_vars="image_id",
            var_name="n_gram_keyword",
            value_name="tfidf_score"
        )

        # 이미지 정보 연결
        image_info = group_df[
            [
                "category",
                "model",
                "product_id",
                "image_order",
                "image_id"
            ]
        ].drop_duplicates()

        tfidf_long = tfidf_long.merge(
            image_info,
            on="image_id",
            how="left"
        )

        # 최종 컬럼 순서
        tfidf_long = tfidf_long[
            [
                "category",
                "model",
                "product_id",
                "image_order",
                "n_gram_keyword",
                "tfidf_score"
            ]
        ]

        all_results.append(tfidf_long)

    # 모든 그룹 결과 합치기
    result = pd.concat(
        all_results,
        ignore_index=True
    )

    return result

tfidf_1 = calculate_tfidf(ngram_1)

tfidf_2 = calculate_tfidf(ngram_2)

tfidf_3 = calculate_tfidf(ngram_3)

print("1-gram TF-IDF:", tfidf_1.shape)
print("2-gram TF-IDF:", tfidf_2.shape)
print("3-gram TF-IDF:", tfidf_3.shape)

display(tfidf_1.head(20))

tfidf_1.sort_values(
    [
        "category",
        "product_id",
        "image_order",
        "tfidf_score"
    ],
    ascending=[
        True,
        True,
        True,
        False
    ]
).head(30)

tfidf_1 = tfidf_1[
    tfidf_1["tfidf_score"] > 0
].copy()

tfidf_2 = tfidf_2[
    tfidf_2["tfidf_score"] > 0
].copy()

tfidf_3 = tfidf_3[
    tfidf_3["tfidf_score"] > 0
].copy()

tfidf_1 = tfidf_1[tfidf_1["tfidf_score"] > 0].reset_index(drop=True)
tfidf_2 = tfidf_2[tfidf_2["tfidf_score"] > 0].reset_index(drop=True)
tfidf_3 = tfidf_3[tfidf_3["tfidf_score"] > 0].reset_index(drop=True)

# 확인할 이미지
target_product_id = 5003416
target_image_order = 1

# 1-gram
result_3 = tfidf_3[
    (tfidf_3["product_id"] == target_product_id) &
    (tfidf_3["image_order"] == target_image_order)
].sort_values("tfidf_score", ascending=False)

print("=== 3-gram TF-IDF ===")
display(result_3)

print(tfidf_1.columns)
print(tfidf_2.columns)
print(tfidf_3.columns)

tfidf_1.to_csv(
    "/content/tfidf_1gram.csv",
    index=False,
    encoding="utf-8-sig"
)

tfidf_2.to_csv(
    "/content/tfidf_2gram.csv",
    index=False,
    encoding="utf-8-sig"
)

tfidf_3.to_csv(
    "/content/tfidf_3gram.csv",
    index=False,
    encoding="utf-8-sig"
)

print("TF-IDF 결과 저장 완료")

