# -*- coding: utf-8 -*-
"""N-gram_ENG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1arCPmEMRMcuDEJotpA0C-keiIS1YTM1K
"""

import pandas as pd
from collections import Counter
from itertools import islice

# 1. 데이터 불러오기
# =========================================================

file_path = "/content/final_correct_data_preprocessed.csv"

df = pd.read_csv(file_path, encoding="utf-8-sig")

print("데이터 크기:", df.shape)
print("\n컬럼 목록:")
print(df.columns.tolist())

print(df.columns.tolist())

# 2. 카테고리별 사용할 모델과 전처리 컬럼
model_config = {
    "bakery": {
        "qwen3": "qwen3_caption_processed"
    },

    "fruits_nuts_rice": {
        "qwen3": "qwen3_caption_processed",
        "hyperclovax": "hyperclovax_caption_processed"
    },

    "convenience_meals": {
        "hyperclovax": "hyperclovax_caption_processed"
    },

    "vegetables": {
        "hyperclovax": "hyperclovax_caption_processed"
    }
}

#3. 토큰화 함수 만들기
def tokenize(text):

    # 결측값 처리
    if pd.isna(text):
        return []

    # 문자열로 변환
    text = str(text).strip()

    # 빈 문자열 처리
    if text == "":
        return []

    # 공백 기준으로 토큰 분리
    return text.split()

# 4.N-gram 생성
def make_ngrams(tokens, n):

    # 토큰 수가 N보다 적으면 생성할 수 없음
    if len(tokens) < n:
        return []

    # N-gram 생성
    ngrams = [
        " ".join(tokens[i:i+n])
        for i in range(len(tokens) - n + 1)
    ]

    return ngrams

# =========================================================
# 5. 카테고리별 N-gram 생성
# =========================================================

def generate_ngram(df, model_config, n):

    results = []

    # 카테고리별로 반복
    for category, models in model_config.items():

        print(f"\n[{category}]")

        # 현재 카테고리 데이터만 선택
        category_df = df[
            df["category"] == category
        ].copy()

        print("데이터 수:", len(category_df))

        # 모델별로 반복
        for model_name, text_column in models.items():

            print(f"  모델: {model_name}")
            print(f"  사용 컬럼: {text_column}")

            # 컬럼 존재 여부 확인
            if text_column not in df.columns:

                print(
                    f"  ⚠️ 컬럼이 존재하지 않습니다: {text_column}"
                )

                continue

            # 이미지별 처리
            for _, row in category_df.iterrows():

                # 전처리된 문장 → 토큰
                tokens = tokenize(
                    row[text_column]
                )

                # N-gram 생성
                ngrams = make_ngrams(
                    tokens,
                    n
                )

                # 동일 N-gram 등장 횟수 계산
                ngram_counts = Counter(ngrams)

                # 결과 저장
                for keyword, count in ngram_counts.items():

                    results.append({

                        "category": row["category"],

                        "model": model_name,

                        "product_id": row["product_id"],

                        "image_order": row["image_order"],

                        "n_gram_keyword": keyword,

                        "ngram_count": count
                    })

    return pd.DataFrame(results)

# 6.1-gram 생성
ngram_1 = generate_ngram(
    df,
    model_config,
    n=1
)

ngram_2 = generate_ngram(
    df,
    model_config,
    n=2
)

ngram_3 = generate_ngram(
    df,
    model_config,
    n=3
)

print("1-gram")
display(ngram_1.head(20))

print("\n2-gram")
display(ngram_2.head(20))

print("\n3-gram")
display(ngram_3.head(20))

print("1-gram:", ngram_1.shape)
print("2-gram:", ngram_2.shape)
print("3-gram:", ngram_3.shape)

ngram_1.to_csv(
    "/content/1gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

ngram_2.to_csv(
    "/content/2gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

ngram_3.to_csv(
    "/content/3gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

print("N-gram CSV 저장 완료")

# 특정 제품의 2-gram 확인
ngram_2[
    ngram_2["product_id"] == ngram_2["product_id"].iloc[0]
].sort_values(
    "ngram_count",
    ascending=False
)

"""#N-gram 생성 비교"""

import pandas as pd

preprocess_df = pd.read_csv(
    "/content/final_correct_data_preprocessed.csv",
    encoding="utf-8-sig"
)

print("전처리 데이터 개수:", len(preprocess_df))

model_config = {
    "bakery": {
        "qwen3": "qwen3_caption_processed"
    },

    "fruits_nuts_rice": {
        "qwen3": "qwen3_caption_processed",
        "hyperclovax": "hyperclovax_caption_processed"
    },

    "convenience_meals": {
        "hyperclovax": "hyperclovax_caption_processed"
    },

    "vegetables": {
        "hyperclovax": "hyperclovax_caption_processed"
    }
}

# 3. 토큰 개수 계산
def tokenize(text):

    if pd.isna(text):
        return []

    text = str(text).strip()

    if text == "":
        return []

    return text.split()

check_results = []

for category, models in model_config.items():

    category_df = preprocess_df[
        preprocess_df["category"] == category
    ]

    for model_name, text_column in models.items():

        if text_column not in preprocess_df.columns:
            print(f"⚠️ 컬럼 없음: {text_column}")
            continue

        for _, row in category_df.iterrows():

            tokens = tokenize(row[text_column])

            token_count = len(tokens)

            # 이론적으로 생성되어야 하는 개수
            expected_1gram = max(token_count, 0)
            expected_2gram = max(token_count - 1, 0)
            expected_3gram = max(token_count - 2, 0)

            check_results.append({
                "category": category,
                "model": model_name,
                "product_id": row["product_id"],
                "image_order": row["image_order"],
                "token_count": token_count,
                "expected_1gram": expected_1gram,
                "expected_2gram": expected_2gram,
                "expected_3gram": expected_3gram
            })

token_check = pd.DataFrame(check_results)

display(token_check.head())

# 4. 실제 N-gram 결과 불러오기

ngram_1 = pd.read_csv(
    "/content/1gram_eng.csv",
    encoding="utf-8-sig"
)

ngram_2 = pd.read_csv(
    "/content/2gram_eng.csv",
    encoding="utf-8-sig"
)

ngram_3 = pd.read_csv(
    "/content/3gram_eng.csv",
    encoding="utf-8-sig"
)

# 5.이미지별 실제 N-gram 개수 계산
actual_1gram = (
    ngram_1
    .groupby(
        ["category", "model", "product_id", "image_order"]
    )["ngram_count"]
    .sum()
    .reset_index(name="actual_1gram")
)

actual_2gram = (
    ngram_2
    .groupby(
        ["category", "model", "product_id", "image_order"]
    )["ngram_count"]
    .sum()
    .reset_index(name="actual_2gram")
)

actual_3gram = (
    ngram_3
    .groupby(
        ["category", "model", "product_id", "image_order"]
    )["ngram_count"]
    .sum()
    .reset_index(name="actual_3gram")
)

# 6.예상 개수와 실제 개수 합치기
check_df = token_check.merge(
    actual_1gram,
    on=[
        "category",
        "model",
        "product_id",
        "image_order"
    ],
    how="left"
)

check_df = check_df.merge(
    actual_2gram,
    on=[
        "category",
        "model",
        "product_id",
        "image_order"
    ],
    how="left"
)

check_df = check_df.merge(
    actual_3gram,
    on=[
        "category",
        "model",
        "product_id",
        "image_order"
    ],
    how="left"
)

check_df[
    ["actual_1gram", "actual_2gram", "actual_3gram"]
] = check_df[
    ["actual_1gram", "actual_2gram", "actual_3gram"]
].fillna(0)

check_df[
    ["actual_1gram", "actual_2gram", "actual_3gram"]
] = check_df[
    ["actual_1gram", "actual_2gram", "actual_3gram"]
].astype(int)

# 7.예상 개수와 실제 개수 비교
check_df["1gram_correct"] = (
    check_df["expected_1gram"]
    == check_df["actual_1gram"]
)

check_df["2gram_correct"] = (
    check_df["expected_2gram"]
    == check_df["actual_2gram"]
)

check_df["3gram_correct"] = (
    check_df["expected_3gram"]
    == check_df["actual_3gram"]
)

display(check_df)

"""예상 N-gram(공백을 기준으로 생성한 토큰 수 기반)과 실제 N-gram 차이가 있는 지 비교"""

problem_df = check_df[
    (~check_df["1gram_correct"]) |
    (~check_df["2gram_correct"]) |
    (~check_df["3gram_correct"])
]

print("문제가 있는 이미지 수:", len(problem_df))

display(problem_df)

target_product_id = 5003416
target_image_order = 1
target_model = "qwen3"

for n in [1, 2, 3]:

    ngram_df = pd.read_csv(
        f"/content/ngram_{n}.csv",
        encoding="utf-8-sig"
    )

    result = ngram_df[
        (ngram_df["product_id"] == target_product_id) &
        (ngram_df["image_order"] == target_image_order) &
        (ngram_df["model"] == target_model)
    ]

    print(f"\n===== {n}-gram =====")
    display(result)

target_product_id = 1002030400
target_image_order = 2
target_model = "hyperclovax"

for n in [1, 2, 3]:

    ngram_df = pd.read_csv(
        f"/content/{n}gram_eng.csv",
        encoding="utf-8-sig"
    )

    result = ngram_df[
        (ngram_df["product_id"] == target_product_id) &
        (ngram_df["image_order"] == target_image_order) &
        (ngram_df["model"] == target_model)
    ]

    print(f"\n===== {n}-gram =====")
    display(result)