# -*- coding: utf-8 -*-
"""TF-IDF_ENG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pz97JaazUWIMXXSPhOYcvr0zwdR37m18
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer

# 영어 N-gram 결과 불러오기
ngram_1 = pd.read_csv(
    "/content/1gram_eng.csv",
    encoding="utf-8-sig"
)

ngram_2 = pd.read_csv(
    "/content/2gram_eng.csv",
    encoding="utf-8-sig"
)

ngram_3 = pd.read_csv(
    "/content/3gram_eng.csv",
    encoding="utf-8-sig"
)

print("1-gram 데이터 수:", len(ngram_1))
print("2-gram 데이터 수:", len(ngram_2))
print("3-gram 데이터 수:", len(ngram_3))

display(ngram_1.head())
display(ngram_2.head())
display(ngram_3.head())

def calculate_tfidf(ngram_df):

    all_results = []

    # 카테고리와 모델 조합별로 그룹화
    for (category, model), group_df in ngram_df.groupby(
        ["category", "model"]
    ):
        print(f"\n현재 그룹: {category} + {model}")
        print("N-gram 데이터 수:", len(group_df))

        group_df = group_df.copy()

        # 이미지별 고유 ID 생성
        group_df["image_id"] = (
            group_df["category"].astype(str)
            + "_"
            + group_df["product_id"].astype(str)
            + "_"
            + group_df["image_order"].astype(str)
        )

        # 이미지별 N-gram 빈도 행렬 생성
        count_matrix = group_df.pivot_table(
            index="image_id",
            columns="n_gram_keyword",
            values="ngram_count",
            aggfunc="sum",
            fill_value=0
        )

        # 해당 카테고리 + 모델 그룹 내에서만 TF-IDF 계산
        transformer = TfidfTransformer()
        tfidf_matrix = transformer.fit_transform(count_matrix)

        # DataFrame 변환
        tfidf_df = pd.DataFrame(
            tfidf_matrix.toarray(),
            index=count_matrix.index,
            columns=count_matrix.columns
        )

        # 이미지-표현별 행 형태로 변환
        tfidf_long = tfidf_df.reset_index().melt(
            id_vars="image_id",
            var_name="n_gram_keyword",
            value_name="tfidf_score"
        )

        # 이미지 메타데이터 연결
        image_info = group_df[
            [
                "category",
                "model",
                "product_id",
                "image_order",
                "image_id"
            ]
        ].drop_duplicates()

        tfidf_long = tfidf_long.merge(
            image_info,
            on="image_id",
            how="left"
        )

        # 컬럼 정리
        tfidf_long = tfidf_long[
            [
                "category",
                "model",
                "product_id",
                "image_order",
                "n_gram_keyword",
                "tfidf_score"
            ]
        ]

        all_results.append(tfidf_long)

    return pd.concat(all_results, ignore_index=True)

tfidf_1 = calculate_tfidf(ngram_1)
tfidf_2 = calculate_tfidf(ngram_2)
tfidf_3 = calculate_tfidf(ngram_3)

print("1-gram TF-IDF:", tfidf_1.shape)
print("2-gram TF-IDF:", tfidf_2.shape)
print("3-gram TF-IDF:", tfidf_3.shape)

display(tfidf_1.head(20))

tfidf_1 = tfidf_1[
    tfidf_1["tfidf_score"] > 0
].reset_index(drop=True)

tfidf_2 = tfidf_2[
    tfidf_2["tfidf_score"] > 0
].reset_index(drop=True)

tfidf_3 = tfidf_3[
    tfidf_3["tfidf_score"] > 0
].reset_index(drop=True)

tfidf_1.sort_values(
    [
        "category",
        "product_id",
        "image_order",
        "tfidf_score"
    ],
    ascending=[
        True,
        True,
        True,
        False
    ]
).head(30)

tfidf_1 = tfidf_1[
    tfidf_1["tfidf_score"] > 0
].copy()

tfidf_2 = tfidf_2[
    tfidf_2["tfidf_score"] > 0
].copy()

tfidf_3 = tfidf_3[
    tfidf_3["tfidf_score"] > 0
].copy()

# 확인할 이미지
target_product_id = 5003416
target_image_order = 1

# 1-gram
result_1 = tfidf_1[
    (tfidf_1["product_id"] == target_product_id) &
    (tfidf_1["image_order"] == target_image_order)
].sort_values("tfidf_score", ascending=False)

print("=== 1-gram TF-IDF ===")
display(result_1)

print("1-gram 모델별 이미지 수")
print(
    ngram_1.groupby(["category", "model"])[
        ["product_id", "image_order"]
    ].apply(lambda x: x.drop_duplicates().shape[0])
)

print("\n1-gram TF-IDF 결과별 데이터 수")
print(
    tfidf_1.groupby(["category", "model"]).size()
)

print(tfidf_1.columns)
print(tfidf_2.columns)
print(tfidf_3.columns)

tfidf_1.to_csv(
    "/content/tfidf_1gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

tfidf_2.to_csv(
    "/content/tfidf_2gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

tfidf_3.to_csv(
    "/content/tfidf_3gram_eng.csv",
    index=False,
    encoding="utf-8-sig"
)

print("TF-IDF 결과 저장 완료")

target_product_id = 5003416
target_image_order = 1
target_model = "qwen3"

for n in [1, 2, 3]:

    tfidf_df = pd.read_csv(
        f"/content/tfidf_{n}gram_eng.csv",
        encoding="utf-8-sig"
    )

    result = tfidf_df[
        (tfidf_df["product_id"] == target_product_id) &
        (tfidf_df["image_order"] == target_image_order) &
        (tfidf_df["model"] == target_model)
    ].copy()

    # TF-IDF 높은 순서
    result = result.sort_values(
        by="tfidf_score",
        ascending=False
    )

    print(f"\n========== {n}-gram ==========")

    display(
        result[
            [
                "n_gram_keyword",
                "tfidf_score"
            ]
        ]
    )